version: "3.8"

services:
  mysqldb:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: wanted_api
    networks:
      springboot-mysql-net:

  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - mysqldb
    networks:
      springboot-mysql-net:
    restart: on-failure

networks:
  springboot-mysql-net: